### ISSUE TITLE
Possible Mac Issue

### ISSUE THREAD

**Issue by Myoldmopar** [lefticus/decent_ci_runner#2]
Should these lines (https://github.com/lefticus/decent_ci_runner/blob/master/setup_ci.sh#L132-L133) be sudo?  @macumber and I are having trouble getting it to run.  It keeps saying it can't find the specified service on those lines, even though the plist file is definitely there.

**Comment by lefticus** [comment]
I would expect it to say it cannot find the service on the very first run of line 132 (since it cannot unload something that it's never loaded before). But I don't _think_ it needs to be sudo.

Have you experimented to verify?

**Comment by macumber** [comment]
I restarted the computer and the service seems to be running, is that the only thing to check for?

**Comment by Myoldmopar** [comment]
I'd watch this page:
https://github.com/NREL/OpenStudioBuildResults/commits/gh-pages   to see if
Marvin successfully makes a PENDING commit soon...

On Tue, Mar 15, 2016 at 1:43 PM, Dan Macumber notifications@github.com
wrote:

> I restarted the computer and the service seems to be running, is that the
> only thing to check for?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lefticus/decent_ci_runner/issues/2#issuecomment-196990597

## 

Edwin Lee, PhD
Engineer, Commercial Buildings Research Staff
National Renewable Energy Laboratory

**Comment by lefticus** [comment]
Ok, it sounds like it worked as expected then.
