### ISSUE TITLE
Window issue installing Python

### ISSUE THREAD

**Issue by macumber** [lefticus/decent_ci_runner#4]
Running the setup script as a non-admin, it gets to the point where it is installing Python.  However, instead of installing it headlessly, a Windows dialog pops up showing the command line options for msiexec, hitting ok generates the following errors:

```
python2 v2.7.11
Installing python2...
Write-Error : [ERROR] Running msiexec with /i "C:\Users\dmacumbe\AppData\Local\
Temp\chocolatey\python2\python2Install.msi" /qn /norestart ALLUSERS=1 TARGETDIR
="C:\tools\python2"  was not successful. Exit code was '1639'.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Start-Chocolat
eyProcessAsAdmin.ps1:46 char:16
+     Write-Error <<<<  $errorMessage
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

Write-Error : python2 did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] [ERROR] Running msiexec with /i "C:\Users\dmacumbe\AppData\Local\Temp\c
hocolatey\python2\python2Install.msi" /qn /norestart ALLUSERS=1 TARGETDIR="C:\t
ools\python2"  was not successful. Exit code was '1639'.
-----------------------
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Chocolat
eyFailure.ps1:30 char:14
+   Write-Error <<<<  $errorMessage
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

Write-Error : Package 'python2 v2.7.11' did not install successfully: [ERROR] R
unning msiexec with /i "C:\Users\dmacumbe\AppData\Local\Temp\chocolatey\python2
\python2Install.msi" /qn /norestart ALLUSERS=1 TARGETDIR="C:\tools\python2"  wa
s not successful. Exit code was '1639'.
At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:9
0 char:28
+                 Write-Error <<<<  "Package `'$installedPackageName v$installe
dPackageVersion`' did not install successfully: $($_.Exception.Message)"
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error
```

**Comment by macumber** [comment]
![error](https://cloud.githubusercontent.com/assets/1327850/13816227/29076008-eb53-11e5-91b2-1b867041198e.jpg)

**Comment by lefticus** [comment]
But it does continue properly if you run as admin explicitly?

**Comment by macumber** [comment]
I manually installed Python but now keep hitting issues with Pandoc (even after manually installing). The msi installer is passed incorrect arguments and pops up an error dialog.  It also appears to be trying to install the programs "--yes" and "--acceptlicense" at the begining of the script

![issue1](https://cloud.githubusercontent.com/assets/1327850/14046421/175a5d5e-f267-11e5-9b3d-80dbc79e38de.jpg)

![issue2](https://cloud.githubusercontent.com/assets/1327850/14046422/1a5194c8-f267-11e5-8d94-c2c65282314f.jpg)

**Comment by macumber** [comment]
I did connect to the NREL Developer VPN which allowed me to install the necessary Ruby gems

**Comment by macumber** [comment]
I don't think the service is starting, maybe because of the install failure with pandoc?

**Comment by lefticus** [comment]
Possibly due to pandoc not installing. It looks like they _just_ released a new version of pandoc on chocolatey and you helpfully picked up that new version, which seems to not be working. 

I just fixed the version of pandoc to 1.16 instead of letting it grab the latest version. Please give the setup another try.

**Comment by macumber** [comment]
I just re-ran the setup script (didn't download a new version of the script) and it downloaded Pandoc 1.16.0.2.  It still pops up the msiexec error and chocolatey returns this

`[ERROR] [ERROR] Running msiexec with /i "C:\Users\dmacumbe\AppData\Local\Temp\chocolatey\pandoc\pandocInstall.msi" /quiet  was not successful. Exit code was '1639'.`

I installed Pandoc 1.16.0.2 manually but the setup still is not starting the service.  At least I think it is not, how will I know when this succeeds?  I'm looking under Services for something like 'decent_ci'.

**Comment by lefticus** [comment]
If you installed pandoc manually, without using `choco` to install it, the system will never know it's installed.

**Comment by lefticus** [comment]
@macumber something about your last message confuses me. You said you "re-ran the setup script (didn't download a new version of the script)" the instructions for installation never have you download a script manually at all. What process are you using for installation?

**Comment by macumber** [comment]
Neither the curl or wget commands worked for me so I just downloaded the setup_ci.sh file and have been running:

```
bash setup_ci.sh true true
```

from the git bash

**Comment by lefticus** [comment]
Were those failures before you upgraded your git bash install? Can you
describe what the error was?

If this most basic aspect of the system is not working correctly, the rest
of it cannot.

Jason

**Comment by lefticus** [comment]
@macumber I notice now also, looking closer at your screenshots, that you are somehow using a version of chocolatey that is nearly 2 years old. I don't know how that is possible with my install scripts.
